import Head from 'next/head'
import Image from 'next/image'
import Script from "next/script"
import { Box, Heading, Text, Container, Grid, Stack, Button, useDisclosure, Modal, ModalBody, ModalContent, ModalHeader, ModalFooter, ModalCloseButton } from '@chakra-ui/react'


export default function Home() {

  const sectionSpacer = [12, 24, 36, 48]
  const sectionSpacerLarge = sectionSpacer.map(num => num + 12)
  const sectionSpacerSmall = sectionSpacer.map(num => num / 2)

  const Headline = ({text, color, children, ...props}) => <Text textTransform="uppercase" fontSize="xs" my={0} letterSpacing={.5} color={color || "gray.600"} {...props}>{children}</Text>
  
  const Testimonial = ({image, quote, name, ...props}) => <Box {...props}>
    <Stack direction="column" align="center" textAlign="center" spacing={6}>
      <Box borderRadius="50%" overflow="hidden" w="125px" h="125px">
        <Image alt="" src={image} width={300} height={300} objectFit="cover" />
      </Box>
      <Text fontSize="sm">{quote}</Text>
      <Headline color="gray.500">— {name}</Headline>
    </Stack>
  </Box>

  const { isOpen, onOpen, onClose } = useDisclosure()

  const BookButton = () => <Button className="book-button" colorScheme="whiteAlpha" onClick={() => onOpen()}>Book an Appointment Online</Button>
  
  return (
    <Box as="main">
      <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TDVXC2W"
      height="0" width="0" style={{display:"none", visibility: "hidden"}}></iframe></noscript>
      <Head>
        <title>Portland Mens Barber — Jaylon Butte — Style Consultant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Script id="gtm" dangerouslySetInnerHTML={{__html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-TDVXC2W');`}} /> 

      <Modal isOpen={isOpen} onOpen={onOpen} onClose={onClose} size="full" isCentered>
        <ModalContent>
          <ModalHeader>
            <ModalCloseButton />
          </ModalHeader>
          <ModalBody>
            <iframe src="//squareup.com/appointments/book/qmbb141ewuo0qw/LGTSXKPQNNMNN/" style={{width: "100%",height: "80vh"}} />
          </ModalBody>
        </ModalContent>
      </Modal>

      <Box textAlign="center" my={sectionSpacer}>
        <Container maxW="container.sm">
          <Stack direction="column">
            <Heading mb={sectionSpacerSmall}>Jaylon Butte</Heading>
            <Stack direction="column" spacing={6}>
              <Heading as="h1" size="sm">Natural Portland Cut &amp; Color</Heading>
              <Heading as="h2" size="xl">Enhance the natural beauty of your hair</Heading>
              <Text>You deserve healthy, natural looking hair. I&apos;ll help you amplify the best qualities of your hair using natural products and techniques.</Text>
            </Stack>
          </Stack>
        </Container>
      </Box>

      <Box mt={sectionSpacer}>
        <Container textAlign="center">
          <Headline>Real Client Photos</Headline>
        </Container>

        <Grid 
          className="client-photos"
          templateColumns={['repeat(2, 1fr)', 'repeat(4, 1fr)']}>
          <Image alt="" src="/images/1.png" width={900} height={900 * 4 / 3} objectFit="cover" />
          <Image alt="" src="/images/3.png" width={900} height={900 * 4 / 3} objectFit="cover" />
          <Image alt="" src="/images/4.png" width={900} height={900 * 4 / 3} objectFit="cover" />
          <Image alt="" src="/images/2.png" width={900} height={900 * 4 / 3} objectFit="cover" />
        </Grid>
      </Box>

      <Box bg="black" color="white" w="100%">
        <Container py={sectionSpacerLarge} textAlign="center">
          <Stack direction="column" align="center" spacing={6}>
            <Stack direction="column" spacing={0}>
              <Headline size="sm" color="white">Schedule an Appointment</Headline>
              <Heading size="xl">Book Online Now</Heading>
            </Stack>
            <BookButton />
          </Stack>
        </Container> 
      </Box>

      <Box my={sectionSpacer}>
        <Container>
          <Stack direction="column" spacing={6}>
            <Stack direction="column" spacing={0} textAlign="center">
              <Headline text="Hair Health + Integrity" my={0} />
              <Heading size="xl" my={0}>I&apos;ll never overdo it</Heading>
            </Stack>
            
            <Grid templateColumns={["100%", "repeat(2, 1fr)"]} gridGap={8} textAlign={["center", "left"]}>
              <Box>
                <Heading size="sm">A Natural Extension of Yourself</Heading>
                <Text>If you&apos;ve had a nightmare coloring experience you know how awful it is to step onto the street feeling like an entirely different person.</Text>
              </Box>
              <Box>
                <Heading size="sm">A Natural Extension of Yourself</Heading>
                <Text>If you&apos;ve had a nightmare coloring experience you know how awful it is to step onto the street feeling like an entirely different person.</Text>
              </Box>
            </Grid>
          </Stack>
        </Container>
      </Box>

      <Box bg="black" color="white" w="100%">
        <Container py={sectionSpacerLarge} textAlign="center" maxW="container.sm">
          <Stack direction="column" align="center" spacing={6}>
            <Stack direction="column">
              <Headline size="sm" color="white">My Promise To You</Headline>
              <Heading size="xl">Free Second Session</Heading>
            </Stack>
            <Text>Want more color? Schedule another appointment within a week of your initial coloring session and Ill further amplify your initial coloring for free</Text>
            <BookButton />
          </Stack>
        </Container> 
      </Box>


      <Box my={sectionSpacer}>
        <Container maxW="container.lg">

          <Grid 
          w="100%"
          templateColumns={['100%', null, null, 'repeat(2, 1fr)']}
          alignItems="center"
          textAlign={["center", null, null, 'left']} gap={12}>
          <Image alt="" src="/images/jaylon.jpg" width={900} height={900 * 4 / 3} />
            <Stack direction="column" spacing={6}>
            
              <Stack direction="column" spacing={0} >
                <Headline>Portland Barber</Headline>
                <Heading size="xl">About Jaylon</Heading>
              </Stack>

              <Text>I want to enhance the beauty that is already within your hair and make your hair dreams reality while keeping health + integrity the main priority.</Text>
            </Stack>
          </Grid>
          
        </Container>
      </Box>

      <Box className="testimonials" my={sectionSpacer}>
        <Container>
          <Grid templateColumns={['100%', null, "repeat(2, 1fr)"]} 
          gridTemplateRows={[null, null, 'repeat(5, auto)']} alignItems="center" gap={8} rowGap={12}>
            <Box 
              gridColumn={[1]}
              gridRowStart={[null, null, 1]} 
              gridRowEnd={[null, null, 3]}> 
            <Testimonial 
              
              name="One" image="/images/3.png" quote="I've been going to Sydney for the past couple of months and she's exceeded my hair goals every time. I started as a blonde and slowly went darker each appointment. I've always been so impressed with Sydneys work and highly recommend her." />
            </Box>
            <Testimonial 
              gridColumn={[2]}
              gridRowStart={[null, null, 2]}
              gridRowEnd={[null, null, 5]}
              name="Two" image="/images/5.png" quote="I've been going to Sydney for the past couple of months and she's exceeded my hair goals every time. I started as a blonde and slowly went darker each appointment. I've always been so impressed with Sydneys work and highly recommend her." />
            
            <Testimonial 
              gridColumn={[1]}
              gridRowStart={[null, null, 4]}
              gridRowEnd={[null, null, 6]}
              name="Three" image="/images/4.png" quote="I've been going to Sydney for the past couple of months and she's exceeded my hair goals every time. I started as a blonde and slowly went darker each appointment. I've always been so impressed with Sydneys work and highly recommend her." />
          </Grid>
        </Container>
      </Box>

      <Box className="studio" my={sectionSpacer}>
        <Grid templateColumns={['1fr 1fr']}>
          <Image alt="" src="/images/studio.jpeg" width={400} height={400 * 4 / 3} objectFit="cover" />
          <Image alt="" src="/images/studio-2.jpeg" width={400} height={400 * 4 / 3} objectFit="cover" />
        </Grid>
      </Box>

      <Box mt={sectionSpacer}>
        <Container>
          <Stack direction="column" textAlign="center">
            <Stack direction="column" spacing={0}>
              <Headline>Find Me At</Headline>
              <Heading size="xl">People on Mars Studio</Heading>
            </Stack>
            <Text>210 SE Madison St, Suite 20, <br/> Portland, OR 97214</Text>
          </Stack>
        </Container>
        <Box mt={sectionSpacer}>
          <Image alt="" src="/images/map.png" width={1922} height={933} objectFit="cover"/>
        </Box>
      </Box>
        

    </Box>
  )
}
